# This is a template you can copy into workspace and edit

# =================
# EXPERIMENT CONFIG
# =================

script = "scripts/simulate_Dp.py"
output_dir = "results/simulate_Dp"
parameters_file = "parameters/Dp_default.toml"
log_file = "logs/Dp_simulator_log.jsonl"
description = "Simulating Dp example"

# ============
# WANDB CONFIG
# ============

[wandb]
enabled = false                        # Whether to use Weights & Biases for logging
project = "connectome-snns"            # W&B project name
entity = ""                            # W&B entity (username or team name), leave empty to use default
tags = []                              # List of tags for organizing runs
notes = ""                             # Notes about this experiment run
